name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1


      - name: Change File Permissions
        run: |
          chmod 600 mmmmm.pem
             
      - name: Build Docker Image
        run: docker build -t your-image-name .

      - name: Deploy to EC2
        run: |
          ssh -i mmmmm.pem ec2-user@18.234.117.166 "sudo docker stop your-container-name || true && sudo docker rm your-container-name || true"
          scp -i mmmmm.pem ec2-user@18.234.117.166:/
          ssh -i mmmmm.pem ec2-user@18.234.117.166 "cd / && sudo docker build -t your-image-name . && sudo docker run -d --name your-container-name -p 3000:3000 your-image-name"
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
