name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id AKIASZRN6DKXG5UN72WJ
          aws configure set aws_secret_access_key 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
          echo "AWS CLI Configuration:"
          aws configure list

      - name: Docker Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 192296131246.dkr.ecr.us-east-1.amazonaws.com

      - name: Debugging Info
        run: |
          echo "AWS CLI Configuration:"
          aws configure list
          echo "Docker Info:"
          docker info

      - name: Build and Push Docker Image to ECR
        run: |
          docker build -t 192296131246.dkr.ecr.us-east-1.amazonaws.com/mm:${{ github.sha }} .
          docker push 192296131246.dkr.ecr.us-east-1.amazonaws.com/mm:${{ github.sha }}
