name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: AKIASZRN6DKXG5UN72WJ
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Docker Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 192296131246.dkr.ecr.us-east-1.amazonaws.com

      - name: Debugging Info
        run: |
          echo "AWS CLI Configuration:"
          aws configure list
          echo "Docker Info:"
          docker info

      - name: Build and Push Docker Image to ECR
        run: |
          docker build -t 192296131246.dkr.ecr.us-east-1.amazonaws.com/mm:${{ github.sha }} .
          docker push 19229613
