name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v2.7.0
        with:
          dockerfile: Dockerfile

      - name: Build Docker Image
        run: docker build -t your-image-name .

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@3.215.190.216 "sudo docker stop your-container-name || true && sudo docker rm your-container-name || true"
          scp -i ${{ secrets.EC2_PRIVATE_KEY }} -r ./ ec2-user@3.215.190.216:/
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ec2-user@3.215.190.216 "cd / && sudo docker build -t your-image-name . && sudo docker run -d --name your-container-name -p 3000:3000 your-image-name"
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
